name: example
description: A example to demonstrate painter.
version: 2.0.0
repository: https://github.com/EPNW/painter

dependencies:
  flutter:
    sdk: flutter
  painter:
    path: ../
  flutter_colorpicker: ^1.1.0
  supabase_flutter: ^2.9.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

flutter:
  uses-material-design: true

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"
